name: Build julia-lsp App
on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, macos, win64]
        include:
        - build: linux
          os: ubuntu-latest
        - build: macos
          os: macos-latest
        - build: win64
          os: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: julia-actions/setup-julia@v1
    - uses: julia-actions/julia-buildpkg@v1
    - name: Get the version number
      shell: bash
      run: |
        LS_VERSION=$(julia --project -e 'using LanguageServer; println(pkgversion(LanguageServer))')
        echo "LS_VERSION=$LS_VERSION" >> $GITHUB_ENV
        echo "LS_VERSION=$LS_VERSION"
    - name: build julia-lsp app
      run: julia contrib/julia-lsp/compile.jl
    - uses: actions/upload-artifact@v3
      with:
        name: julia-lsp-v${{ env.LS_VERSION }}-${{ matrix.build }}
        path: ${{ github.workspace }}
